In [5]:
import pandas as pd
import numpy as np

data = {
    "name" : ['A','B','C'],
    'marks' : [50,60,70],
    'percent' : [70,80,90],
}
df = pd.DataFrame(data)
df

  name  marks  percent
0    A     50       70
1    B     60       80
2    C     70       90

In [6]:
df["new"]=[10,20,30]
df

  name  marks  percent  new
0    A     50       70   10
1    B     60       80   20
2    C     70       90   30

## Apply,Concat,Merge,GroupBy

app ni 1st arg ma 
funcion = like sum ,mean etc

In [7]:
df.apply("sum")

name       ABC
marks      180
percent    240
new         60
dtype: object

In [8]:
df.apply(np.sum)

name       ABC
marks      180
percent    240
new         60
dtype: object

In [10]:
df.apply(np.sum,axis=0)

name       ABC
marks      180
percent    240
new         60
dtype: object

In [ ]:
df.set_index('name',inplace=True)

In [17]:
df

      marks  percent  new
name
A        50       70   10
B        60       80   20
C        70       90   30

In [18]:
df.apply(np.sum,axis=1)

name
A    130
B    160
C    190
dtype: int64

In [ ]:
df.apply(lambda x: x+5)

      marks  percent  new
name
A        55       75   15
B        65       85   25
C        75       95   35

In [ ]:
df['percent'].apply(lambda x:'pass' if x>75 else 'fail')

name
A    fail
B    pass
C    pass
Name: percent, dtype: object

In [25]:
df

      marks  percent  new
name
A        50       70   10
B        60       80   20
C        70       90   30

In [27]:
df["marks_extra"] = df['marks'].apply(lambda x:x+4)

In [ ]:
df["marks_extra"] = df['marks'].apply(lambda x:x+4 if x>60 else x)

In [31]:
df

      marks  percent  new  marks_extra
name
A        50       70   10           50
B        60       80   20           60
C        70       90   30           74

In [ ]:
def grade(x):
    if x>70:
        return 'A'
    elif x>55:
        return 'B'
    else:
        return 'C'

'B'

In [37]:
def grade(x):
    if x["marks_extra"]>70:
        return 'A'
    elif x["marks_extra"]>55:
        return 'B'
    else:
        return 'C'
df["Grade"] = df.apply(grade,axis=1)

axis 1 ma aakhi row jay

In [38]:
df

      marks  percent  new  marks_extra Grade
name
A        50       70   10           50     C
B        60       80   20           60     B
C        70       90   30           74     A

In [41]:
for i in df:
    print(i)

marks
percent
new
marks_extra
Grade

In [43]:
for i in df.values:
    print(i)

[50 70 10 50 'C']
[60 80 20 60 'B']
[70 90 30 74 'A']

In [44]:
for i in df.index:
    print(i)

A
B
C

In [45]:
for i in df.columns:
    print(i)

marks
percent
new
marks_extra
Grade

In [48]:
for i in df:
    print(df[i])

name
A    50
B    60
C    70
Name: marks, dtype: int64
name
A    70
B    80
C    90
Name: percent, dtype: int64
name
A    10
B    20
C    30
Name: new, dtype: int64
name
A    50
B    60
C    74
Name: marks_extra, dtype: int64
name
A    C
B    B
C    A
Name: Grade, dtype: object

In [49]:
def fun(x):
    return x*2
df.apply(fun)

      marks  percent  new  marks_extra Grade
name
A       100      140   20          100    CC
B       120      160   40          120    BB
C       140      180   60          148    AA

In [ ]:
def fun(x,val):
    return x*val
df.apply(fun,args=(3,))

      marks  percent  new  marks_extra Grade
name
A       150      210   30          150   CCC
B       180      240   60          180   BBB
C       210      270   90          222   AAA

## CONCAT

In [51]:
df1 = pd.DataFrame({'A':[1,2],'B':[6,7]})
df2 = pd.DataFrame({'A':[3,4],'B':[9,5]})

print(df1)
print(df2)

   A  B
0  1  6
1  2  7
   A  B
0  3  9
1  4  5

In [ ]:
pd.concat([df1,df2])

   A  B
0  1  6
1  2  7
0  3  9
1  4  5

In [ ]:
pd.concat([df1,df2],axis=1)

   A  B  A  B
0  1  6  3  9
1  2  7  4  5

In [54]:
df1 = pd.DataFrame({'A':[1,2],'B':[6,7]})
df2 = pd.DataFrame({'A':[3,4],'D':[9,5]})
print(df1)
print(df2)

   A  B
0  1  6
1  2  7
   A  D
0  3  9
1  4  5

inner ma command colum hase ae rese
outer ma badhi column lese

default outer che

In [55]:
pd.concat([df1,df2],join='outer')

   A    B    D
0  1  6.0  NaN
1  2  7.0  NaN
0  3  NaN  9.0
1  4  NaN  5.0

In [ ]:
pd.concat([df1,df2],join='inner')

   A
0  1
1  2
0  3
1  4

In [ ]:
pd.concat([df1,df2],join='inner',ignore_index=True)

   A
0  1
1  2
2  3
3  4

In [61]:
df1 = pd.DataFrame({'A':[1,2],'E':[6,7]})
df2 = pd.DataFrame({'F':[3,4],'D':[9,5]})
print(df1)
print(df2)

   A  E
0  1  6
1  2  7
   F  D
0  3  9
1  4  5

In [ ]:
pd.concat([df1,df2])

     A    E    F    D
0  1.0  6.0  NaN  NaN
1  2.0  7.0  NaN  NaN
0  NaN  NaN  3.0  9.0
1  NaN  NaN  4.0  5.0

In [ ]:
pd.concat([df1,df2],sort=True)

     A    D    E    F
0  1.0  NaN  6.0  NaN
1  2.0  NaN  7.0  NaN
0  NaN  9.0  NaN  3.0
1  NaN  5.0  NaN  4.0

In [ ]:
pd.concat([df1,df2],join="inner")

Empty DataFrame
Columns: []
Index: [0, 1, 0, 1]

In [ ]:
pd.concat([df1,df2],join="inner").shape

(4, 0)

In [68]:
empty = pd.DataFrame({})
empty

Empty DataFrame
Columns: []
Index: []

In [ ]:
print(empty)

Empty DataFrame
Columns: []
Index: []

In [70]:
empty.shape

(0, 0)

# panel data analysis system (pandas)