## MERGE

In [1]:
import pandas as pd

df1 = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['a','b','c','d'],
    'dept_id':[10,20,30,40]
})
df2 = pd.DataFrame({
    'dept_id':[10,20,30],
    'dept' : ['IT','HR','FINANCE']
})
print(df1)
print(df2)

   emp_id name  dept_id
0       1    a       10
1       2    b       20
2       3    c       30
3       4    d       40
   dept_id     dept
0       10       IT
1       20       HR
2       30  FINANCE

In [2]:
pd.merge(df1,df2,on='dept_id',how="inner")

   emp_id name  dept_id     dept
0       1    a       10       IT
1       2    b       20       HR
2       3    c       30  FINANCE

In [3]:
pd.merge(df1,df2,on='dept_id',how="left")

   emp_id name  dept_id     dept
0       1    a       10       IT
1       2    b       20       HR
2       3    c       30  FINANCE
3       4    d       40      NaN

In [4]:
pd.merge(df1,df2,on='dept_id',how="outer")

   emp_id name  dept_id     dept
0       1    a       10       IT
1       2    b       20       HR
2       3    c       30  FINANCE
3       4    d       40      NaN

In [5]:
pd.merge(df1,df2,on='dept_id',how="right")

   emp_id name  dept_id     dept
0       1    a       10       IT
1       2    b       20       HR
2       3    c       30  FINANCE

In [6]:


df1 = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['a','b','c','d'],
    'dept_id':[10,20,30,40]
})
df2 = pd.DataFrame({
    'd_id':[10,20,30],
    'dept' : ['IT','HR','FINANCE']
})
print(df1)
print(df2)

   emp_id name  dept_id
0       1    a       10
1       2    b       20
2       3    c       30
3       4    d       40
   d_id     dept
0    10       IT
1    20       HR
2    30  FINANCE

In [7]:
pd.merge(df1,df2,left_on='dept_id',right_on="d_id")

   emp_id name  dept_id  d_id     dept
0       1    a       10    10       IT
1       2    b       20    20       HR
2       3    c       30    30  FINANCE

In [8]:
pd.merge(df1,df2,left_index=True,right_index=True)

   emp_id name  dept_id  d_id     dept
0       1    a       10    10       IT
1       2    b       20    20       HR
2       3    c       30    30  FINANCE

In [ ]:
pd.merge(df1,df2,left_index=True,right_index=True,how="outer")

   emp_id name  dept_id  d_id     dept
0       1    a       10  10.0       IT
1       2    b       20  20.0       HR
2       3    c       30  30.0  FINANCE
3       4    d       40   NaN      NaN

In [17]:


df1 = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['a','b','c','d'],
    'dept_id':[10,20,10,40]
})
df2 = pd.DataFrame({
    'd_id':[10,20,30],
    'name' : ['IT','HR','FINANCE']
})
print(df1)
print(df2)

   emp_id name  dept_id
0       1    a       10
1       2    b       20
2       3    c       10
3       4    d       40
   d_id     name
0    10       IT
1    20       HR
2    30  FINANCE

In [22]:
pd.merge(df1,df2,left_index=True,right_index=True,how="outer",suffixes=['_emp','_dept'])

   emp_id name_emp  dept_id  d_id name_dept
0       1        a       10  10.0        IT
1       2        b       20  20.0        HR
2       3        c       10  30.0   FINANCE
3       4        d       40   NaN       NaN

In [23]:
pd.merge(df1,df2,left_on='dept_id',right_on='d_id')

   emp_id name_x  dept_id  d_id name_y
0       1      a       10    10     IT
1       2      b       20    20     HR
2       3      c       10    10     IT

In [24]:
pd.merge(df1,df2,left_on='dept_id',right_on='d_id',sort=False)

   emp_id name_x  dept_id  d_id name_y
0       1      a       10    10     IT
1       2      b       20    20     HR
2       3      c       10    10     IT

In [25]:
pd.merge(df1,df2,left_on='dept_id',right_on='d_id',sort=True)

   emp_id name_x  dept_id  d_id name_y
0       1      a       10    10     IT
1       3      c       10    10     IT
2       2      b       20    20     HR

## GROUPBY

In [30]:
df = pd.read_csv('loan.csv')
df

,Unnamed: 0.1,Unnamed: 0,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
0,0,0,PAIDOFF,1000,30,09-08-2016,10-07-2016,45,High School or Below,male
1,2,2,PAIDOFF,1000,30,09-08-2016,10-07-2016,33,Bechalor,female
2,3,3,PAIDOFF,1000,15,09-08-2016,9/22/2016,27,college,male
3,4,4,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,female
4,6,6,PAIDOFF,1000,30,09-09-2016,10-08-2016,29,college,male
5,7,7,PAIDOFF,1000,30,09-09-2016,10-08-2016,36,college,male
6,8,8,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,male
7,9,9,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
8,10,10,PAIDOFF,300,7,09-10-2016,9/16/2016,29,college,male
9,11,11,PAIDOFF,1000,15,09-10-2016,10-09-2016,39,High School or Below,male
10,12,12,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male
11,13,13,PAIDOFF,900,7,09-10-2016,9/16/2016,26,college,female
12,14,14,PAIDOFF,1000,7,09-10-2016,9/16/2016,27,High School or Below,male
13,15,15,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
14,16,16,PAIDOFF,1000,30,09-10-2016,10-09-2016,40,High School or Below,male
15,17,17,PAIDOFF,1000,15,09-10-2016,9/24/2016,32,High School or Below,male
16,18,18,PAIDOFF,1000,30,09-10-2016,10-09-2016,32,High School or Below,male
17,19,19,PAIDOFF,800,30,09-10-2016,10-09-2016,26,college,male
18,20,20,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male

In [31]:
df.drop(['Unnamed: 0.1','Unnamed: 0'],axis=1,inplace=True)

In [33]:
df['education'].unique()

array(['High School or Below', 'Bechalor', 'college'], dtype=object)

In [34]:
df.groupby("education")

In [40]:
df.groupby("education").mean(numeric_only=True)

                        Principal      terms        age
education
Bechalor              1000.000000  30.000000  33.000000
High School or Below  1000.000000  21.166667  35.833333
college                883.333333  22.416667  27.750000

In [41]:
df.groupby("education").sum(numeric_only=True)

                      Principal  terms  age
education
Bechalor                   1000     30   33
High School or Below       6000    127  215
college                   10600    269  333

In [42]:
df.groupby('education').agg['mean','sum','max']

TypeError: 'method' object is not subscriptable

In [45]:
df.groupby('education').agg({'Principal':['mean','max'],
                             'terms':['max']})

                        Principal       terms
                             mean   max   max
education
Bechalor              1000.000000  1000    30
High School or Below  1000.000000  1000    30
college                883.333333  1000    30

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   loan_status     19 non-null     object
 1   Principal       19 non-null     int64
 2   terms           19 non-null     int64
 3   effective_date  19 non-null     object
 4   due_date        19 non-null     object
 5   age             19 non-null     int64
 6   education       19 non-null     object
 7   Gender          19 non-null     object
dtypes: int64(3), object(5)
memory usage: 1.3+ KB

In [48]:
df.groupby(["education","Gender",'loan_status']).mean(numeric_only=True)

                                         Principal      terms        age
education            Gender loan_status
Bechalor             female PAIDOFF         1000.0  30.000000  33.000000
High School or Below male   PAIDOFF         1000.0  21.166667  35.833333
college              female PAIDOFF          950.0  18.500000  27.000000
                     male   PAIDOFF          870.0  23.200000  27.900000

In [49]:
df.groupby(["education"]).describe()

                     Principal                                           \
                         count         mean         std     min     25%
education
Bechalor                   1.0  1000.000000         NaN  1000.0  1000.0
High School or Below       6.0  1000.000000    0.000000  1000.0  1000.0
college                   12.0   883.333333  203.752672   300.0   800.0

                                             terms             ...        \
                         50%     75%     max count       mean  ...   75%
education                                                      ...
Bechalor              1000.0  1000.0  1000.0   1.0  30.000000  ...  30.0
High School or Below  1000.0  1000.0  1000.0   6.0  21.166667  ...  30.0
college               1000.0  1000.0  1000.0  12.0  22.416667  ...  30.0

                             age                                         \
                       max count       mean       std   min   25%   50%
education
Bechalor              30.0   1.0  33.000000       NaN  33.0  33.0  33.0
High School or Below  30.0   6.0  35.833333  6.615638  27.0  32.0  35.5
college               30.0  12.0  27.750000  2.864358  26.0  26.0  26.5


                        75%   max
education
Bechalor              33.00  33.0
High School or Below  39.75  45.0
college               28.25  36.0

[3 rows x 24 columns]

In [50]:
df.groupby(["education"]).size()

education
Bechalor                 1
High School or Below     6
college                 12
dtype: int64

In [51]:
df.groupby(["education"]).count()

,loan_status,Principal,terms,effective_date,due_date,age,Gender
education,,,,,,,
Bechalor,1,1,1,1,1,1,1
High School or Below,6,6,6,6,6,6,6
college,12,12,12,12,12,12,12

In [52]:
df.groupby(["education"]).nunique()

,loan_status,Principal,terms,effective_date,due_date,age,Gender
education,,,,,,,
Bechalor,1,1,1,1,1,1,1
High School or Below,1,1,3,2,4,5,1
college,1,4,3,3,5,5,2

In [54]:
df.groupby(["education"])['terms'].apply(lambda x:x+4)

education
Bechalor              1     34
High School or Below  0     34
                      9     19
                      12    11
                      14    34
                      15    19
                      16    34
college               2     19
                      3     34
                      4     34
                      5     34
                      6     34
                      7     19
                      8     11
                      10    34
                      11    11
                      13    19
                      17    34
                      18    34
Name: terms, dtype: int64

In [58]:
def new(x):
    x["High_term"] = x['terms']>x['terms'].mean()
    return x
df.groupby(["education"]).apply(new)

C:\Users\91940\AppData\Local\Temp\ipykernel_13816\2518935148.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby(["education"]).apply(new)

                        loan_status  Principal  terms effective_date  \
education
Bechalor             1      PAIDOFF       1000     30     09-08-2016
High School or Below 0      PAIDOFF       1000     30     09-08-2016
                     9      PAIDOFF       1000     15     09-10-2016
                     12     PAIDOFF       1000      7     09-10-2016
                     14     PAIDOFF       1000     30     09-10-2016
                     15     PAIDOFF       1000     15     09-10-2016
                     16     PAIDOFF       1000     30     09-10-2016
college              2      PAIDOFF       1000     15     09-08-2016
                     3      PAIDOFF       1000     30     09-09-2016
                     4      PAIDOFF       1000     30     09-09-2016
                     5      PAIDOFF       1000     30     09-09-2016
                     6      PAIDOFF       1000     30     09-09-2016
                     7      PAIDOFF        800     15     09-10-2016
                     8      PAIDOFF        300      7     09-10-2016
                     10     PAIDOFF       1000     30     09-10-2016
                     11     PAIDOFF        900      7     09-10-2016
                     13     PAIDOFF        800     15     09-10-2016
                     17     PAIDOFF        800     30     09-10-2016
                     18     PAIDOFF       1000     30     09-10-2016

                           due_date  age             education  Gender  \
education
Bechalor             1   10-07-2016   33              Bechalor  female
High School or Below 0   10-07-2016   45  High School or Below    male
                     9   10-09-2016   39  High School or Below    male
                     12   9/16/2016   27  High School or Below    male
                     14  10-09-2016   40  High School or Below    male
                     15   9/24/2016   32  High School or Below    male
                     16  10-09-2016   32  High School or Below    male
college              2    9/22/2016   27               college    male
                     3   10-08-2016   28               college  female
                     4   10-08-2016   29               college    male
                     5   10-08-2016   36               college    male
                     6   10-08-2016   28               college    male
                     7    9/24/2016   26               college    male
                     8    9/16/2016   29               college    male
                     10  10-09-2016   26               college    male
                     11   9/16/2016   26               college  female
                     13   9/24/2016   26               college    male
                     17  10-09-2016   26               college    male
                     18  10-09-2016   26               college    male

                         High_term
education
Bechalor             1       False
High School or Below 0        True
                     9       False
                     12      False
                     14       True
                     15      False
                     16       True
college              2       False
                     3        True
                     4        True
                     5        True
                     6        True
                     7       False
                     8       False
                     10       True
                     11      False
                     13      False
                     17       True
                     18       True

In [59]:
df.groupby(["education"]).nth(0)

,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
0,PAIDOFF,1000,30,09-08-2016,10-07-2016,45,High School or Below,male
1,PAIDOFF,1000,30,09-08-2016,10-07-2016,33,Bechalor,female
2,PAIDOFF,1000,15,09-08-2016,9/22/2016,27,college,male

In [60]:
df.groupby(["education"]).nth(1)

,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
3,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,female
9,PAIDOFF,1000,15,09-10-2016,10-09-2016,39,High School or Below,male

In [61]:
df.groupby(["education"]).nth([0,1])

,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
0,PAIDOFF,1000,30,09-08-2016,10-07-2016,45,High School or Below,male
1,PAIDOFF,1000,30,09-08-2016,10-07-2016,33,Bechalor,female
2,PAIDOFF,1000,15,09-08-2016,9/22/2016,27,college,male
3,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,female
9,PAIDOFF,1000,15,09-10-2016,10-09-2016,39,High School or Below,male

In [62]:
df.sort_index()

,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
0,PAIDOFF,1000,30,09-08-2016,10-07-2016,45,High School or Below,male
1,PAIDOFF,1000,30,09-08-2016,10-07-2016,33,Bechalor,female
2,PAIDOFF,1000,15,09-08-2016,9/22/2016,27,college,male
3,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,female
4,PAIDOFF,1000,30,09-09-2016,10-08-2016,29,college,male
5,PAIDOFF,1000,30,09-09-2016,10-08-2016,36,college,male
6,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,male
7,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
8,PAIDOFF,300,7,09-10-2016,9/16/2016,29,college,male
9,PAIDOFF,1000,15,09-10-2016,10-09-2016,39,High School or Below,male
10,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male
11,PAIDOFF,900,7,09-10-2016,9/16/2016,26,college,female
12,PAIDOFF,1000,7,09-10-2016,9/16/2016,27,High School or Below,male
13,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
14,PAIDOFF,1000,30,09-10-2016,10-09-2016,40,High School or Below,male
15,PAIDOFF,1000,15,09-10-2016,9/24/2016,32,High School or Below,male
16,PAIDOFF,1000,30,09-10-2016,10-09-2016,32,High School or Below,male
17,PAIDOFF,800,30,09-10-2016,10-09-2016,26,college,male
18,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male

In [63]:
df.sort_index(axis=1)

,Gender,Principal,age,due_date,education,effective_date,loan_status,terms
0,male,1000,45,10-07-2016,High School or Below,09-08-2016,PAIDOFF,30
1,female,1000,33,10-07-2016,Bechalor,09-08-2016,PAIDOFF,30
2,male,1000,27,9/22/2016,college,09-08-2016,PAIDOFF,15
3,female,1000,28,10-08-2016,college,09-09-2016,PAIDOFF,30
4,male,1000,29,10-08-2016,college,09-09-2016,PAIDOFF,30
5,male,1000,36,10-08-2016,college,09-09-2016,PAIDOFF,30
6,male,1000,28,10-08-2016,college,09-09-2016,PAIDOFF,30
7,male,800,26,9/24/2016,college,09-10-2016,PAIDOFF,15
8,male,300,29,9/16/2016,college,09-10-2016,PAIDOFF,7
9,male,1000,39,10-09-2016,High School or Below,09-10-2016,PAIDOFF,15
10,male,1000,26,10-09-2016,college,09-10-2016,PAIDOFF,30
11,female,900,26,9/16/2016,college,09-10-2016,PAIDOFF,7
12,male,1000,27,9/16/2016,High School or Below,09-10-2016,PAIDOFF,7
13,male,800,26,9/24/2016,college,09-10-2016,PAIDOFF,15
14,male,1000,40,10-09-2016,High School or Below,09-10-2016,PAIDOFF,30
15,male,1000,32,9/24/2016,High School or Below,09-10-2016,PAIDOFF,15
16,male,1000,32,10-09-2016,High School or Below,09-10-2016,PAIDOFF,30
17,male,800,26,10-09-2016,college,09-10-2016,PAIDOFF,30
18,male,1000,26,10-09-2016,college,09-10-2016,PAIDOFF,30

In [64]:
df.sort_index(axis=1,ascending=False)

,terms,loan_status,effective_date,education,due_date,age,Principal,Gender
0,30,PAIDOFF,09-08-2016,High School or Below,10-07-2016,45,1000,male
1,30,PAIDOFF,09-08-2016,Bechalor,10-07-2016,33,1000,female
2,15,PAIDOFF,09-08-2016,college,9/22/2016,27,1000,male
3,30,PAIDOFF,09-09-2016,college,10-08-2016,28,1000,female
4,30,PAIDOFF,09-09-2016,college,10-08-2016,29,1000,male
5,30,PAIDOFF,09-09-2016,college,10-08-2016,36,1000,male
6,30,PAIDOFF,09-09-2016,college,10-08-2016,28,1000,male
7,15,PAIDOFF,09-10-2016,college,9/24/2016,26,800,male
8,7,PAIDOFF,09-10-2016,college,9/16/2016,29,300,male
9,15,PAIDOFF,09-10-2016,High School or Below,10-09-2016,39,1000,male
10,30,PAIDOFF,09-10-2016,college,10-09-2016,26,1000,male
11,7,PAIDOFF,09-10-2016,college,9/16/2016,26,900,female
12,7,PAIDOFF,09-10-2016,High School or Below,9/16/2016,27,1000,male
13,15,PAIDOFF,09-10-2016,college,9/24/2016,26,800,male
14,30,PAIDOFF,09-10-2016,High School or Below,10-09-2016,40,1000,male
15,15,PAIDOFF,09-10-2016,High School or Below,9/24/2016,32,1000,male
16,30,PAIDOFF,09-10-2016,High School or Below,10-09-2016,32,1000,male
17,30,PAIDOFF,09-10-2016,college,10-09-2016,26,800,male
18,30,PAIDOFF,09-10-2016,college,10-09-2016,26,1000,male

In [67]:
df.sort_values(by='age')

,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
18,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male
7,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
17,PAIDOFF,800,30,09-10-2016,10-09-2016,26,college,male
10,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male
11,PAIDOFF,900,7,09-10-2016,9/16/2016,26,college,female
13,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
2,PAIDOFF,1000,15,09-08-2016,9/22/2016,27,college,male
12,PAIDOFF,1000,7,09-10-2016,9/16/2016,27,High School or Below,male
3,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,female
6,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,male
4,PAIDOFF,1000,30,09-09-2016,10-08-2016,29,college,male
8,PAIDOFF,300,7,09-10-2016,9/16/2016,29,college,male
16,PAIDOFF,1000,30,09-10-2016,10-09-2016,32,High School or Below,male
15,PAIDOFF,1000,15,09-10-2016,9/24/2016,32,High School or Below,male
1,PAIDOFF,1000,30,09-08-2016,10-07-2016,33,Bechalor,female
5,PAIDOFF,1000,30,09-09-2016,10-08-2016,36,college,male
9,PAIDOFF,1000,15,09-10-2016,10-09-2016,39,High School or Below,male
14,PAIDOFF,1000,30,09-10-2016,10-09-2016,40,High School or Below,male
0,PAIDOFF,1000,30,09-08-2016,10-07-2016,45,High School or Below,male

In [69]:
df.sort_values(by=['age','terms'])

,loan_status,Principal,terms,effective_date,due_date,age,education,Gender
11,PAIDOFF,900,7,09-10-2016,9/16/2016,26,college,female
7,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
13,PAIDOFF,800,15,09-10-2016,9/24/2016,26,college,male
10,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male
17,PAIDOFF,800,30,09-10-2016,10-09-2016,26,college,male
18,PAIDOFF,1000,30,09-10-2016,10-09-2016,26,college,male
12,PAIDOFF,1000,7,09-10-2016,9/16/2016,27,High School or Below,male
2,PAIDOFF,1000,15,09-08-2016,9/22/2016,27,college,male
3,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,female
6,PAIDOFF,1000,30,09-09-2016,10-08-2016,28,college,male
8,PAIDOFF,300,7,09-10-2016,9/16/2016,29,college,male
4,PAIDOFF,1000,30,09-09-2016,10-08-2016,29,college,male
15,PAIDOFF,1000,15,09-10-2016,9/24/2016,32,High School or Below,male
16,PAIDOFF,1000,30,09-10-2016,10-09-2016,32,High School or Below,male
1,PAIDOFF,1000,30,09-08-2016,10-07-2016,33,Bechalor,female
5,PAIDOFF,1000,30,09-09-2016,10-08-2016,36,college,male
9,PAIDOFF,1000,15,09-10-2016,10-09-2016,39,High School or Below,male
14,PAIDOFF,1000,30,09-10-2016,10-09-2016,40,High School or Below,male
0,PAIDOFF,1000,30,09-08-2016,10-07-2016,45,High School or Below,male

## PB147

In [70]:
df = pd.read_csv("supermarket_sales.csv")

In [71]:
df.head(8)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,01-05-2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,03-08-2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,02-08-2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,18:30,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,14:36,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38,Ewallet,735.60,4.761905,36.7800,8.0

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     996 non-null    float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   995 non-null    float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [74]:
df.isnull().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Total                      0
Date                       0
Time                       0
Payment                    0
cogs                       4
gross margin percentage    0
gross income               0
Rating                     5
dtype: int64

In [77]:
df['cogs'].fillna(df['cogs'].mean(),inplace=True)

C:\Users\91940\AppData\Local\Temp\ipykernel_13816\4198857905.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cogs'].fillna(df['cogs'].mean(),inplace=True)

In [78]:
df['Rating'].fillna(df['Rating'].mean(),inplace=True)

C:\Users\91940\AppData\Local\Temp\ipykernel_13816\3843224868.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Rating'].fillna(df['Rating'].mean(),inplace=True)

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Total                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [83]:
df.loc[(df["Quantity"]<3.0) & ((df["Rating"]>8.5) | (df["Total"]>600))].shape[0]

45

In [87]:
df.loc[(df["Customer type"]=="Member")]["Total"].sum()

164223.44400000002

In [88]:
df.loc[(df["Customer type"]=="Normal")]["Total"].sum()

158743.305

In [93]:
print(df.groupby("Customer type")["Total"].sum(numeric_only=True))

Customer type
Member    164223.444
Normal    158743.305
Name: Total, dtype: float64

In [108]:
df.groupby("Payment")["gross income"].sum()/df["gross income"].sum()*100

Payment
Cash           34.742453
Credit card    31.200448
Ewallet        34.057099
Name: gross income, dtype: float64

In [84]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,01-05-2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,03-08-2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,02-08-2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3