In [41]:
import pandas as pd
import plotly.express as px

In [42]:
data = pd.read_csv('social_media_engagement.csv')
df = pd.DataFrame(data)
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [43]:
df.nunique()

post_id            100
platform             3
post_type            5
post_time           99
likes               93
comments            85
shares              96
post_day             7
sentiment_score      3
dtype: int64

In [44]:
fig = px.bar(df,
             x='platform',
             y='likes',
             width = 800,
             height = 500,
             title = 'Social Media Analysis',
             color = 'post_type',
             barmode = 'group',
             hover_data = ['post_day','sentiment_score'],
             pattern_shape = 'post_type',
             text_auto = True)
fig.show()

In [45]:
fig = px.bar(df,
             x='platform',
             y='likes',
             width = 800,
             height = 500,
             title = 'Social Media Analysis',
             color = 'post_type',
             barmode = 'stack',
             hover_data = ['post_day','sentiment_score'],
             pattern_shape = 'post_type',
             text_auto = True)
fig.show()

## Sactter plot

In [46]:
fig = px.scatter(df,
             x='likes',
             y='comments',
             title = 'Likes v/s comments')
fig.show()

In [47]:
fig = px.scatter(df,
             x='likes',
             y='comments',
             title = 'Likes v/s comments',
             color = 'platform',
             size = 'comments',)
fig.show()

In [48]:
fig = px.scatter(df,
             x='likes',
             y='comments',
             title = 'Likes v/s comments',
             color = 'platform',
             size = 'comments',
             symbol='platform')
fig.show()

## 3d sctter plot

In [49]:
fig = px.scatter_3d(df,
             x='likes',
             y='comments',
             z = 'shares',
             color = 'likes',
             title = '3d sctter plot',)
fig.show()

In [50]:
fig = px.scatter_3d(df,
             x='likes',
             y='comments',
             z = 'shares',
             color = 'likes',
             size = 'likes',
             symbol='post_type',
             title = '3d sctter plot',)
fig.show()

In [51]:
fig =  px.scatter_matrix(df,
                         dimensions=['likes','comments','platform'],
                         color='comments',
                         title='scatter_matrix')
fig.show()

In [52]:
fig = px.scatter(df,
             x='likes',
             y='comments',
             width = 900,
             height = 500,
             title = 'sctter plot',
             color = 'platform',
             size = 'comments',
             color_discrete_map={
                 'Facebook' : 'Blue',
                 'Instagram' : 'red',
                 'Twitter' : 'green'
             },
             color_discrete_sequence=['red','green','blue'],
             symbol='platform',
             facet_col='sentiment_score',
             facet_row='platform')
fig.show()

In [53]:
fig = px.scatter(df,
             x='likes',
             y='comments',
             width = 900,
             height = 500,
             title = 'sctter plot',
             color = 'platform',
             size = 'comments',
             color_discrete_map={
                 'Facebook' : 'Blue',
                 'Instagram' : 'red',
                 'Twitter' : 'green'
             },
             color_discrete_sequence=['red','green','blue'],
             symbol='platform',
             facet_col='post_type',
             facet_row='platform')
fig.show()

## Line Chart

In [54]:
fig = px.line(df,
              x= 'likes',
              y = 'comments',
              title='Likes v/s comments')
fig.show()

In [55]:
fig = px.line(df,
              x= 'likes',
              y = 'comments',
              markers=True,
              title='Likes v/s comments')
fig.show()

In [56]:
fig = px.line(df.iloc[0:10],
              x= 'likes',
              y = 'comments',
              color='platform',
              width=800,
              height=500,
              markers=True,
              hover_data=['post_type'],
              color_discrete_sequence=['red','blue','green'],
              title='Likes v/s comments')
fig.show()

# Histogram

In [78]:
data = pd.read_csv('social_media_engagement.csv')
df = pd.DataFrame(data)
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [79]:
fig = px.histogram(df,
                   x = 'likes',
                   color='platform',
                   text_auto=True,
                   color_discrete_map={
                       'Facebook':'Yellow',
                       'Instagram':'skyblue',
                       'Twitter' : 'red'
                   },
                   histfunc='count',
                   color_discrete_sequence=['yellow','skublue','red'],
                   
                   )
fig.show()

In [80]:
data = {
    'Marks' : [40,45,50,55,60,65,70,75,80,85],
    'Gender' : ['M','F','M','F','M','F','M','F','M','F']
}
df = pd.DataFrame(data)
fig = px.histogram(df,
                   x = 'Marks',
                   nbins=4,
                   color='Gender',
                   pattern_shape='Gender',
                   text_auto=True)
fig.show()

# pie chart

In [81]:
data = {
    'Month':['Jan','Feb','Mar','Apr','Jan','Feb','Mar','Apr'],
    'Sales':[100,120,140,160,90,110,130,150],
    'Region' : ['North','North','North','North','South','South','South','South']   
}
df = pd.DataFrame(data)
df

  Month  Sales Region
0   Jan    100  North
1   Feb    120  North
2   Mar    140  North
3   Apr    160  North
4   Jan     90  South
5   Feb    110  South
6   Mar    130  South
7   Apr    150  South

In [82]:
fig = px.pie(df,
             values='Sales',
             names='Month',
             color_discrete_sequence=['blue','green','orange','red'],
             )
fig.update_traces(textinfo = 'percent+label',
                  textposition = 'inside',
                  pull = [0,0,0.1,0.1])
fig.show()