In [6]:
import pandas as pd
import numpy as np
data = pd.read_csv("production_analysis_dataset.csv")
df = pd.DataFrame(data)
df

# Q1. Find the total units produced by each product_category.

In [13]:
import pandas as pd
import numpy as np

df.groupby("product_category").sum(numeric_only=True)['units_produced']

# Q2. Calculate the average profit for each factory.

In [12]:
df.groupby("factory").mean(numeric_only=True)["profit"]

# Q3. Find the total defective_units for each shift.

In [14]:
df.groupby('shift').sum()['defective_units']

# Q4. Calculate the average production_time_hr for each supervisor.

In [15]:
df.groupby('supervisor').mean(numeric_only=True)['production_time_hr']

In [ ]:
df.groupby()

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [16]:
df.groupby(["factory",'shift']).sum(numeric_only=True)['energy_consumption_kwh']

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

In [23]:
df.groupby('product_category').agg({
    'units_produced' : 'sum',
    'profit' : 'mean',
    'defective_units' : 'max',
})

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

In [25]:
df.groupby('factory').agg(
    {
        'production_time_hr':'mean',
        'machine_downtime_hr':'median'
    }
)

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

In [27]:
df.groupby('shift').agg(
    {
        'profit' : ['min','max'],
        'units_produced':'mean'
    }
)

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

In [28]:
df.groupby("supervisor").agg(
    {
        'units_produced':'sum',
        'defective_units':'sum'
    }
)

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

In [32]:
df['defect_rate'] = df.apply(lambda x : x['defective_units']/x['units_produced'],axis = 1)
df

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [36]:
df.groupby(['factory']).apply(lambda x : x['profit'].max()-x['profit'].min())

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [40]:
df.groupby(['product_category']).apply(lambda x : x['units_produced'].idxmax())

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

In [51]:
df['efficiency_score'] = df.apply(lambda x : x['units_produced']/x['production_time_hr'],axis=1)
df

# Q14. Find how many times each product_category appears in the dataset.

In [59]:
df.groupby('product_category').size()

# Q15. Count the number of records for each shift.

In [ ]:
df.groupby('shift').size()

In [26]:
df.head(5)

# Q16. Find the most frequent supervisor using value_counts().

In [54]:
df['supervisor'].value_counts()

# Q17. Sort the dataset by profit in descending order.

In [ ]:
df.sort_values(by='profit',ascending=False)

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending

In [65]:
df.sort_values(by=['product_category','units_produced'],ascending=[True,False])

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate,efficiency_score
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,0.021739,84.975369
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,0.036090,86.363636
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,0.048338,101.689708
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,0.017161,84.788360
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156,91.212121
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,0.025818,79.589041
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,0.019678,61.361142
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,0.043564,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,0.067729,72.438672
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,0.050104,53.459821
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,0.052521,60.947503
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,0.071111,64.562410
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,0.033708,56.978233
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,0.052392,52.827918
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,0.044855,51.285521
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,0.086253,52.624113
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,0.026866,39.273154
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559,85.824742
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,0.013657,79.111645
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,0.017214,68.562232
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,0.063796,87.569832
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,0.045089,75.455650
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,0.081800,70.461095
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414,68.005739
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,0.018692,63.126844
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,0.021583,45.227766
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,0.021687,55.259654
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,0.086387,46.813725
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,0.078431,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,0.104956,38.324022
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,0.090634,38.133641
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,0.024316,39.878788
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,0.038217,34.392114
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,0.017799,91.964286
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,0.016207,79.510309
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,0.050167,78.787879
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,0.008576,68.266979
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,0.065844,72.429210
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118,53.363229
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,0.020362,47.021277
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,0.034404,49.209932
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,0.049763,54.876463
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,0.095355,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,0.027708,58.468336
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,0.079487,59.360731
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,0.039683,42.567568
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,0.082621,47.885402
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,0.057637,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,0.096346,41.232877

In [67]:
data = pd.read_csv('supermarket_sales (1).csv')
df = pd.DataFrame(data)
df.head(10)

,Unnamed: 0,invoice id,branch,city,customer type,gender,product line,unit price,quantity,tax 5%,total,date,time,payment,cogs,gross margin percentage,gross income,rating,day_of_week
0,0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,13:08,Ewallet,522.830000,4.761905,26.1415,9.1,Saturday
1,1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29,Cash,76.400000,4.761905,3.8200,9.6,Friday
2,2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.310000,4.761905,16.2155,7.4,Sunday
3,3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,20:33,Ewallet,465.760000,4.761905,23.2880,8.4,Sunday
4,4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37,Ewallet,604.170000,4.761905,30.2085,5.3,Friday
5,5,699-14-3026,C,Naypyitaw,Normal,Male,Electronic accessories,85.39,7,29.8865,627.6165,25-03-2019,18:30,Ewallet,597.730000,4.761905,29.8865,4.1,Monday
6,6,355-53-5943,A,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,25-02-2019,14:36,Ewallet,413.040000,4.761905,20.6520,5.8,Monday
7,7,315-22-5665,C,Naypyitaw,Normal,Female,Home and lifestyle,73.56,10,36.7800,772.3800,24-02-2019,11:38,Ewallet,735.600000,4.761905,36.7800,8.0,Sunday
8,8,665-32-9167,A,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,10-01-2019,17:15,Credit card,72.520000,4.761905,3.6260,7.2,Thursday
9,9,692-92-5582,B,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,20-02-2019,13:27,Credit card,307.969398,4.761905,8.2260,5.9,Wednesday

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               1000 non-null   int64
 1   invoice id               1000 non-null   object
 2   branch                   1000 non-null   object
 3   city                     1000 non-null   object
 4   customer type            996 non-null    object
 5   gender                   995 non-null    object
 6   product line             1000 non-null   object
 7   unit price               1000 non-null   float64
 8   quantity                 1000 non-null   int64
 9   tax 5%                   1000 non-null   float64
 10  total                    1000 non-null   float64
 11  date                     1000 non-null   object
 12  time                     1000 non-null   object
 13  payment                  1000 non-null   object
 14  cogs                     1000 non-null   float64
 15  gross margin percentage  1000 non-null   float64
 16  gross income             996 non-null    float64
 17  rating                   1000 non-null   float64
 18  day_of_week              1000 non-null   object
dtypes: float64(7), int64(2), object(10)
memory usage: 148.6+ KB

In [72]:
df.fillna(df.mean(numeric_only=True),inplace=True)
df

,Unnamed: 0,invoice id,branch,city,customer type,gender,product line,unit price,quantity,tax 5%,total,date,time,payment,cogs,gross margin percentage,gross income,rating,day_of_week
0,0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,Saturday
1,1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29,Cash,76.40,4.761905,3.8200,9.6,Friday
2,2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Sunday
3,3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,Sunday
4,4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,29-01-2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2,Tuesday
996,996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,02-03-2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4,Saturday
997,997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,09-02-2019,13:22,Cash,31.84,4.761905,1.5920,7.7,Saturday
998,998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,22-02-2019,15:33,Cash,65.82,4.761905,3.2910,4.1,Friday
999,999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,18-02-2019,13:28,Cash,618.38,4.761905,30.9190,6.6,Monday

In [74]:
df['customer type'].fillna(df['customer type'].mode()[0],inplace = True)
df['gender'].fillna(df['gender'].mode()[0],inplace = True)
df

C:\Users\91940\AppData\Local\Temp\ipykernel_23308\1130930306.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0],inplace = True)

,Unnamed: 0,invoice id,branch,city,customer type,gender,product line,unit price,quantity,tax 5%,total,date,time,payment,cogs,gross margin percentage,gross income,rating,day_of_week
0,0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,Saturday
1,1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29,Cash,76.40,4.761905,3.8200,9.6,Friday
2,2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Sunday
3,3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,Sunday
4,4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Friday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,29-01-2019,13:46,Ewallet,40.35,4.761905,2.0175,6.2,Tuesday
996,996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,02-03-2019,17:16,Ewallet,973.80,4.761905,48.6900,4.4,Saturday
997,997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,09-02-2019,13:22,Cash,31.84,4.761905,1.5920,7.7,Saturday
998,998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,22-02-2019,15:33,Cash,65.82,4.761905,3.2910,4.1,Friday
999,999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,18-02-2019,13:28,Cash,618.38,4.761905,30.9190,6.6,Monday

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               1000 non-null   int64
 1   invoice id               1000 non-null   object
 2   branch                   1000 non-null   object
 3   city                     1000 non-null   object
 4   customer type            1000 non-null   object
 5   gender                   1000 non-null   object
 6   product line             1000 non-null   object
 7   unit price               1000 non-null   float64
 8   quantity                 1000 non-null   int64
 9   tax 5%                   1000 non-null   float64
 10  total                    1000 non-null   float64
 11  date                     1000 non-null   object
 12  time                     1000 non-null   object
 13  payment                  1000 non-null   object
 14  cogs                     1000 non-null   float64
 15  gross margin percentage  1000 non-null   float64
 16  gross income             1000 non-null   float64
 17  rating                   1000 non-null   float64
 18  day_of_week              1000 non-null   object
dtypes: float64(7), int64(2), object(10)
memory usage: 148.6+ KB

In [76]:
df.head()

,Unnamed: 0,invoice id,branch,city,customer type,gender,product line,unit price,quantity,tax 5%,total,date,time,payment,cogs,gross margin percentage,gross income,rating,day_of_week
0,0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,Saturday
1,1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29,Cash,76.40,4.761905,3.8200,9.6,Friday
2,2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Sunday
3,3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,Sunday
4,4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Friday

In [77]:
df.groupby("branch")['gross income'].sum()

branch
A    5057.160500
B    5064.615727
C    5289.837227
Name: gross income, dtype: float64

In [78]:
df['product line'].value_counts().head()

product line
Fashion accessories       178
Food and beverages        174
Electronic accessories    170
Sports and travel         166
Home and lifestyle        160
Name: count, dtype: int64

In [80]:
df.groupby("branch")['rating'].mean(numeric_only=True)

branch
A    7.026536
B    6.822735
C    7.072866
Name: rating, dtype: float64

In [99]:
df.groupby('payment').size()

payment
Cash           344
Credit card    311
Ewallet        345
dtype: int64

In [91]:
df.head()

,Unnamed: 0,invoice id,branch,city,customer type,gender,product line,unit price,quantity,tax 5%,total,date,time,payment,cogs,gross margin percentage,gross income,rating,day_of_week,days
0,0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,05-01-2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,Saturday,Weekend
1,1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,08-03-2019,10:29,Cash,76.40,4.761905,3.8200,9.6,Friday,Weekday
2,2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,03-03-2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Sunday,Weekend
3,3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,27-01-2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4,Sunday,Weekend
4,4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,08-02-2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3,Friday,Weekday

In [94]:
def new(x):
    if x['day_of_week'] == 'Sunday' or x['day_of_week'] == 'Saturday':
        return 'Weekend'
    else:
        return 'Weekday'
df['days'] = df.apply(new,axis=1)

df.groupby('days')['gross income'].sum()

days
Weekday    10599.694727
Weekend     4811.918727
Name: gross income, dtype: float64

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               1000 non-null   int64
 1   invoice id               1000 non-null   object
 2   branch                   1000 non-null   object
 3   city                     1000 non-null   object
 4   customer type            1000 non-null   object
 5   gender                   1000 non-null   object
 6   product line             1000 non-null   object
 7   unit price               1000 non-null   float64
 8   quantity                 1000 non-null   int64
 9   tax 5%                   1000 non-null   float64
 10  total                    1000 non-null   float64
 11  date                     1000 non-null   object
 12  time                     1000 non-null   object
 13  payment                  1000 non-null   object
 14  cogs                     1000 non-null   float64
 15  gross margin percentage  1000 non-null   float64
 16  gross income             1000 non-null   float64
 17  rating                   1000 non-null   float64
 18  day_of_week              1000 non-null   object
dtypes: float64(7), int64(2), object(10)
memory usage: 148.6+ KB