In [ ]:
import pandas as pd
data = pd.read_csv("ipl-matches.csv")
df = pd.DataFrame(data)
df

In [ ]:
df.tail(15)

In [ ]:
df.head(15)

In [ ]:
df.info()

In [ ]:
print(df.shape)
print(df.shape[0])
print(df.shape[1])
print(len(df))

In [ ]:
df.describe() #jeni int ae aavse

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [ ]:
df.describe(include='all')# badhu aavse

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
count,9.500000e+02,899,950,950,950,950,950,950,950,950,946,946,950,932.000000,19,946,950,950,950,950
unique,NaN,33,706,15,80,18,18,49,18,2,2,18,4,NaN,1,262,932,937,58,60
top,NaN,Mumbai,2014-05-10,2013,Final,Royal Challengers Bangalore,Mumbai Indians,Eden Gardens,Mumbai Indians,field,N,Mumbai Indians,Wickets,NaN,D/L,AB de Villiers,"['RD Gaikwad', 'F du Plessis', 'MM Ali', 'SK R...","['RV Uthappa', 'G Gambhir', 'MK Pandey', 'SA Y...",AK Chaudhary,S Ravi
freq,NaN,159,2,76,15,126,119,77,123,599,932,131,509,NaN,19,25,2,2,95,83
mean,8.304852e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.056867,NaN,NaN,NaN,NaN,NaN,NaN
std,3.375678e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.633109,NaN,NaN,NaN,NaN,NaN,NaN
min,3.359820e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.012612e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,8.297380e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.175372e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,1.312200e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.000000,NaN,NaN,NaN,NaN,NaN,NaN